# Generated by Django 5.1.2 on 2024-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacredito',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='cuentacredito',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
