# Generated by Django 5.1.2 on 2024-10-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0009_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
