# Generated by Django 5.1.2 on 2024-10-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0010_alter_cliente_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
